### PR TITLE
Better linting setup, fix pyproject.toml requires, add pre-commit

### PR DESCRIPTION
**Pull request by gsheni**
- Added commands to Makefile to **handle** linting, and creating the .tar.gz + .whl file (for PyPI).
- Added [pre-commit](https://pre-commit.com/) so that you don't have to run `make lint-fix` before committing.
  - Added a few hooks.
  - These are set and forget. It will run when you do `git commit -m "commit msg"`.
- Due to pre-commit running on all files you now have the following benefit: 
  - Absolute imports everywhere.
  - Double quotes everywhere.
  - Trailing commas everywhere.
- `black` linting had been added ("uncompromising Python code formatter").
- `isort` has been added for sorted imports.
- `pyproject.toml` should not contain package requirements in `requires`. These have been removed.
- `version` in `setup.cfg` should specify the absolute path (to avoid importing unneeded module (the reason you had the previous error)).
- Added `.[dev]` extra requires. This contains the linting dependencies.
- Added lint check workflow to GitHub Actions CI.

### CODE REVIEW

**Comment by kmax12** [comment]
thanks for the contribution! looks like there is a misconfigured action preventing the linting from running

**Comment by gsheni** [comment]
- @kmax12 Woops, I just fixed that https://github.com/kmax12/isodata/pull/11/commits/9b6e76aedf0978d64f14f6c2dfafa9087529867b
  - It was due to missing quotes

**Comment by kmax12** [comment]
looks like everything is passing. will take a look tomorrow!

**Comment by kmax12** [comment]
merged in. thank you so much, really appreciate it!

**Pull request merged**
